sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IaFinwHnH4AL0KPqxOQt24z1Ix672BVY7L4ybYcgu4CTiObJIO3WmZ0HOfuDXKV4y85ns7GfDn0ATlH2DZMyX4UorN3WOC4H+QI6LEtn7LSP8QX7jugTB+6ti/BHYmBLIQPpSCGht3AsWjju8gbsUg7jJJoomR0pw4uZVi3qUZ22v5yltjsq3inZ2rmLyXHU7HoG9IC/vESUQ4bRB1w32ZVC3v00howIrVF5u1hSJ1+XwpDTDuP5xu65MSMoeqeL5GGnJeEBACEadQPHXROqUf0XwnomvqM4/MNhTdojk3UESwL+KK1QgA7JO/jzQ/gwuG1dYp/NAL7hZyvJEIuEKyYoAbaeFbFxhjW3IrFxP6IY3aMK4uD1a7J1f0IcVCOrUOAEkeq3Ai569fIwibUTSU0kIdhOnsdVoOw49nIw4foJj/0E1jLgAvtqSpn8AJSGed7M1/4IMekxmzH2IPau++v3uJE1evHrxjzCwJ7+Kh3MaelPa9V/9PkRFwEMy4QHzh4jNxq7EQiKR+8MiryFKDzXhL7AZ/KW152CVGjuM0dvdBrKUOAJP0Y63jdeoet8PtYoK4SsIsiaMy9wSRAHIN0nvbwSlVUAXD+Il5C20lMr8tK8ZzdkBsW/bOvPb+oVS7p+PD23y3l3LXjYDPeXCLoq7lXR41O6+Xs85eBT3uA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Blind-Spot_4920
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy